### PR TITLE
check if table is in whitelist before invalidating

### LINKED ISSUE #9: johnny cache sets table keys even for blacklisted tables
this increases traffic to memcached and can be avoided.

### PR DESCRIPTION
**Pull request by viralshah**
fixes #9

### CODE REVIEW

**Comment by jmoiron** [comment]
How would that patch work if it was this instead?

``` python
def invalidate(*tables, **kwargs):
    """Invalidate the current generation for one or more tables.  The arguments
    can be either strings representing database table names or models.  Pass in
    kwarg ``using`` to set the database."""
    backend = get_backend()
    db = kwargs.get('using', 'default')

    if disallowed_table(*tables):
        return

    def resolve(x):
        if isinstance(x, basestring):
            return x
        return x._meta.db_table

    if backend._patched:
        for t in map(resolve, tables):
            backend.keyhandler.invalidate_table(t, db)
```

EDIT: It can be done even before the backend is fetched as well.

**Comment by jmoiron** [comment]
On second thought, `invalidate` is designed to be run from user code.  Johnny's invalidation uses the keyhandler directly.  I am going to go through and make sure we don't do unnecessary invalidations from the write compiler patches, but I think running `invalidate` should work regardless of the settings.

**Comment by viralshah** [comment]
yes I was just going to comment on that :). 
Also when are you releasing 1.4.1 :) ?

**Comment by jmoiron** [comment]
Maybe after this..   the point of johnny is performance.  Performance and correctness.  The two points...

There is a (small) correctness issue with 1.4.0 (fixed with https://github.com/jmoiron/johnny-cache/commit/f5b64457ddd7b49abf52a9e9a67ccf1a8bdfa0dd) and now a possible performance issue.  I'm running tests on something which will be a lot less conservative about skipping blacklisted tables during normal johnny operation.  It should make life for people who use Whitelists a lot better.  

I'm still having second thoughts about making `invalidate` skip it though;  in my patch i'm testing now, the `backend.flush_query_cache` function will also skip fussing about with the blacklist.

**Comment by viralshah** [comment]
the patch I sent it applicable to whitelists too. basically if table is not in whitelist we shouldn't set the table_key for it on _monkey_write.

Ah and also I am assuming you mean `invalidate_table`

**Comment by jmoiron** [comment]
Yeah, I want that behavior in the sql execution paths, but not on `johnny.cache.invalidate`;  johnny itself never calls this function itself (it always uses the keyhandler directly), and if there's a performance issue with using this then it is in user code and the user can use `disallowed_table` to avoid extra writes.

Hows https://github.com/jmoiron/johnny-cache/commit/0f16eb185db32c33bda8f6d7e5e58a6a73c11fe4 look?

**Comment by viralshah** [comment]
looks good. thanks for quick fix!

**Pull request closed without merging**
